//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLTabulka1.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLTabulka1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný RAZITKO;DATABAZE;POPIS;DATABAZE1;RAZITKO1;POPIS1;TEXTBOX;TAB;vazba;sloupec;Dokument;Zákazník;Projekt;Task;Autor;Revize;Typ;Zámek;Cislo;Profese;Třídění
        ///SUBJECT1;NAZ_PROJ;NÁZEV PROJEKTU;C_PROJ;PROJ_NUM;číslo projektu;1;Projekt;ID;cislo;ID;ID;ID;ID;ID;ID;ID;ID;ID;ID;ID
        ///SUBJECT2;NAZ_UKOL;STUPEŇ PROJEKTU;CYCOSTATUS;;;2;;;;nazev;jmeno;cislo;cislo;jmeno;Popis;dokument;lock;predcisli;Profese;
        ///SUBJECT3;;;NAZ_PROJ;SUBJECT1;název projektu;3;Projekt;ID;nazev;počet_stran;adresa;nazev;jmeno;prijmeni;datum;pripona;;str [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string SPOLECNE2_old {
            get {
                return ResourceManager.GetString("SPOLECNE2.old", resourceCulture);
            }
        }
    }
}
